### ISSUE TITLE
Missing fastutil-extra artifact for 8.5.5?

### ISSUE THREAD

**Issue by dpapworth-qc** [vigna/fastutil#263]
Hey,

I've noticed that there isn't a 8.5.5 version for fastutil-extra. I get compilation errors when trying to build using just fastutil 8.5.5 by itself. e.g.

    ... error: cannot access Function
    class file for it.unimi.dsi.fastutil.Function not found

    ... error: cannot access Hash
    class file for it.unimi.dsi.fastutil.Hash not found

These compilation errors are generated when trying to use Int2LongMap::get and Int2LongOpenHashMap::put respectively. I can fix these errors by explicitly including fastutil-extra 8.5.4 in my gradle dependencies.

Has fastutil-extra been inadvertently dropped from the dependencies for fastutil?

Thanks,
Damien.

**Comment by vigna** [comment]
I think that, in retrospect, I'll damn forever the day I listened to people asking for a smaller jar. This only ended up in a bunch of solutions each of which was nonworking for someone. And to bugs such as the one you reported (thanks!), which I'm going to investigate immediately.

**Comment by vigna** [comment]
The new version has a different split strategy: please have a look at the website.

**Comment by vigna** [comment]
OK. Wrong "Exports:" clause in BND configuration. I'll publish immediately a fix.

**Comment by dpapworth-qc** [comment]
Thanks for the quick response!

**Comment by kno10** [comment]
Maven central still only has the broken 8.5.5:

https://mvnrepository.com/artifact/it.unimi.dsi/fastutil

**Comment by vigna** [comment]
No no, it's up there—try in search. Probably those pages are updated offline.
